services:
  php:
    build: .
    volumes:
      - .:/app:rw
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_test
    ports:
      - "3306:3306"
    volumes:
      - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
